### ISSUE TITLE
v2.2.0 could not work with typescript 2.2.1

### ISSUE THREAD

**Issue by dennyx** [dominhhai/koa-log4js#6]
Hi dominhhai,
After upgrading koa-log4js to 2.2.0, it could not work well as complaining:
`
\node_modules\.2.2.0@koa-log4\koa-logger.js:50
  return async (ctx, next) => {
               ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
`

typescript version as:
`
$ tsc -v
Version 2.2.1
`

while v2.1.0 works well;
May u kindly help on it, thanks~

**Comment by dominhhai** [comment]
@dennyx  hi, thanks for your reporting.
`v2.2.0` use  native `async-await`.
If your want to use `yield` function, please use `v2.1.0` instead of.

**Comment by dennyx** [comment]
@dominhhai thanks for the kindly feedback, i will change in my code;thanks~
